spring:
  profiles:
    active: dev
--- 
spring:
  profiles: dev
  application:
    name: myspringcloud-config-dev

server:
  port: 8003
---
spring:
  profiles: test
  application:
    name: myspringcloud-config-test

